version: '2'
services:
  mongo:
    image: sameersbn/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
    - /data/dbdocker:/var/lib/mongodb
    restart: always
    tmpfs:
    - /tmp
    - /run
    - /mnt/sda1/var/lib/docker/tmp/

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  pyglb:
    build: ./src
    ports:
      - "8001:8001"
    links:
      - mongo:mongo
      - memcached:memcached
    command: python app.py --port=8001